export const romanianCounties = [
  { "name": "Alba", "alpha2": "AB", "alpha3": "RO-AB" },
  { "name": "Arad", "alpha2": "AR", "alpha3": "RO-AR" },
  { "name": "Argeș", "alpha2": "AG", "alpha3": "RO-AG" },
  { "name": "Bacău", "alpha2": "BC", "alpha3": "RO-BC" },
  { "name": "Bihor", "alpha2": "BH", "alpha3": "RO-BH" },
  { "name": "Bistrița-Năsăud", "alpha2": "BN", "alpha3": "RO-BN" },
  { "name": "Botoșani", "alpha2": "BT", "alpha3": "RO-BT" },
  { "name": "Brașov", "alpha2": "BV", "alpha3": "RO-BV" },
  { "name": "Brăila", "alpha2": "BR", "alpha3": "RO-BR" },
  { "name": "Sector 1 (Bucuresti)", "alpha2": "B1", "alpha3": "SECTOR1" },
  { "name": "Sector 2 (Bucuresti)", "alpha2": "B2", "alpha3": "SECTOR2" },
  { "name": "Sector 3 (Bucuresti)", "alpha2": "B3", "alpha3": "SECTOR3" },
  { "name": "Sector 4 (Bucuresti)", "alpha2": "B4", "alpha3": "SECTOR4" },
  { "name": "Sector 5 (Bucuresti)", "alpha2": "B5", "alpha3": "SECTOR5" },
  { "name": "Sector 6 (Bucuresti)", "alpha2": "B6", "alpha3": "SECTOR6" },
  { "name": "Buzău", "alpha2": "BZ", "alpha3": "RO-BZ" },
  { "name": "Caraș-Severin", "alpha2": "CS", "alpha3": "RO-CS" },
  { "name": "Călărași", "alpha2": "CL", "alpha3": "RO-CL" },
  { "name": "Cluj", "alpha2": "CJ", "alpha3": "RO-CJ" },
  { "name": "Constanța", "alpha2": "CT", "alpha3": "RO-CT" },
  { "name": "Covasna", "alpha2": "CV", "alpha3": "RO-CV" },
  { "name": "Dâmbovița", "alpha2": "DB", "alpha3": "RO-DB" },
  { "name": "Dolj", "alpha2": "DJ", "alpha3": "RO-DJ" },
  { "name": "Galați", "alpha2": "GL", "alpha3": "RO-GL" },
  { "name": "Giurgiu", "alpha2": "GR", "alpha3": "RO-GR" },
  { "name": "Gorj", "alpha2": "GJ", "alpha3": "RO-GJ" },
  { "name": "Harghita", "alpha2": "HR", "alpha3": "RO-HR" },
  { "name": "Hunedoara", "alpha2": "HD", "alpha3": "RO-HD" },
  { "name": "Ialomița", "alpha2": "IL", "alpha3": "RO-IL" },
  { "name": "Iași", "alpha2": "IS", "alpha3": "RO-IS" },
  { "name": "Ilfov", "alpha2": "IF", "alpha3": "RO-IF" },
  { "name": "Maramureș", "alpha2": "MM", "alpha3": "RO-MM" },
  { "name": "Mehedinți", "alpha2": "MH", "alpha3": "RO-MH" },
  { "name": "Mureș", "alpha2": "MS", "alpha3": "RO-MS" },
  { "name": "Neamț", "alpha2": "NT", "alpha3": "RO-NT" },
  { "name": "Olt", "alpha2": "OT", "alpha3": "RO-OT" },
  { "name": "Prahova", "alpha2": "PH", "alpha3": "RO-PH" },
  { "name": "Satu Mare", "alpha2": "SM", "alpha3": "RO-SM" },
  { "name": "Sălaj", "alpha2": "SJ", "alpha3": "RO-SJ" },
  { "name": "Sibiu", "alpha2": "SB", "alpha3": "RO-SB" },
  { "name": "Suceava", "alpha2": "SV", "alpha3": "RO-SV" },
  { "name": "Teleorman", "alpha2": "TR", "alpha3": "RO-TR" },
  { "name": "Timiș", "alpha2": "TM", "alpha3": "RO-TM" },
  { "name": "Tulcea", "alpha2": "TL", "alpha3": "RO-TL" },
  { "name": "Vaslui", "alpha2": "VS", "alpha3": "RO-VS" },
  { "name": "Vâlcea", "alpha2": "VL", "alpha3": "RO-VL" },
  { "name": "Vrancea", "alpha2": "VN", "alpha3": "RO-VN" }
];
