export const countries = [
  { country: "United States", id: "1", icon: null },
  { country: "Canada", id: "2", icon: null },
  { country: "Brazil", id: "3", icon: null },
  { country: "United Kingdom", id: "4", icon: null },
  { country: "Australia", id: "5", icon: null },
  { country: "Germany", id: "6", icon: null },
  { country: "France", id: "7", icon: null },
  { country: "Italy", id: "8", icon: null },
  { country: "Spain", id: "9", icon: null },
  { country: "Mexico", id: "10", icon: null },
  { country: "India", id: "11", icon: null },
  { country: "China", id: "12", icon: null },
  { country: "Russia", id: "13", icon: null },
  { country: "South Korea", id: "14", icon: null },
  { country: "Japan", id: "15", icon: null },
  { country: "Argentina", id: "16", icon: null },
  { country: "South Africa", id: "17", icon: null },
  { country: "Egypt", id: "18", icon: null },
  { country: "Nigeria", id: "19", icon: null },
  { country: "Saudi Arabia", id: "20", icon: null },
  { country: "Turkey", id: "21", icon: null },
  { country: "Sweden", id: "22", icon: null },
  { country: "Norway", id: "23", icon: null },
  { country: "Netherlands", id: "24", icon: null },
  { country: "Belgium", id: "25", icon: null },
  { country: "Switzerland", id: "26", icon: null },
  { country: "New Zealand", id: "27", icon: null },
  { country: "Greece", id: "28", icon: null },
  { country: "Poland", id: "29", icon: null },
  { country: "Thailand", id: "30", icon: null },
];
